name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run migrations
        env:
          SECRET_KEY: "TEST_KEY"
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        run: python manage.py migrate --noinput

      - name: Run tests
        env:
          SECRET_KEY: "TEST_KEY"
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        run: python manage.py test --noinput


  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      -   name: Deploy to server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd /var/www/Homework_5
              
              echo "--- PULL LATEST CODE ---"
              git pull origin main
              
              echo "--- CREATE COMPLETE .env FILE ---"
              cat > .env << EOL
              SECRET_KEY=${{ secrets.SECRET_KEY }}
              DEBUG=False
              POSTGRES_DB=${{ secrets.POSTGRES_DB }}
              POSTGRES_USER=${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
              POSTGRES_HOST=db
              POSTGRES_PORT=5432
              NAME_DB=${{ secrets.POSTGRES_DB }}
              USER_DB=${{ secrets.POSTGRES_USER }}
              PASSWORD_DB=${{ secrets.POSTGRES_PASSWORD }}
              ALLOWED_HOSTS=*
              EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
              EMAIL_HOST=localhost
              EMAIL_PORT=587
              EMAIL_USE_TLS=True
              EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
              EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
              STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}
              EOL
              
              echo "--- RESTART DOCKER ---"
              docker compose -f docker-compose.yaml down
              docker compose -f docker-compose.yaml build --no-cache
              docker compose -f docker-compose.yaml up -d
              
              echo "--- WAIT FOR SERVICES ---"
              sleep 10
              
              echo "--- APPLY MIGRATIONS ---"
              docker compose -f docker-compose.yaml exec -T backend python manage.py migrate --noinput
              
              echo "--- COLLECTSTATIC ---"
              docker compose -f docker-compose.yaml exec -T backend python manage.py collectstatic --noinput
              
              echo "--- DEPLOYMENT COMPLETE ---"