name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run migrations
        env:
          SECRET_KEY: "TEST_KEY"
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        run: python manage.py migrate --noinput

      - name: Run tests
        env:
          SECRET_KEY: "TEST_KEY"
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        run: python manage.py test --noinput


  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      -   name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      -   name: Deploy to server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
              echo '--- CLEAN AND CLONE REPOSITORY ---' &&
              rm -rf /var/www/Homework_5 &&
              git clone https://github.com/xzista/Homework_5 /var/www/Homework_5 &&
              cd /var/www/Homework_5 &&
            
              echo '--- CLEAN DOCKER CACHE ---' &&
              docker system prune -af &&
              docker volume prune -f &&
            
              echo '--- BUILD & RESTART DOCKER ---' &&
              docker compose down || true &&
              docker compose --env-file <(echo \\
                'SECRET_KEY=${{ secrets.SECRET_KEY }}\\
                POSTGRES_DB=${{ secrets.POSTGRES_DB }}\\
                POSTGRES_USER=${{ secrets.POSTGRES_USER }}\\
                POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\\
                POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}\\
                POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}'\\
              ) build --no-cache &&
            
              docker compose --env-file <(echo \\
                'SECRET_KEY=${{ secrets.SECRET_KEY }}\\
                POSTGRES_DB=${{ secrets.POSTGRES_DB }}\\
                POSTGRES_USER=${{ secrets.POSTGRES_USER }}\\
                POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\\
                POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}\\
                POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}'\\
              ) up -d &&
            
              echo '--- WAIT FOR SERVICES TO START ---' &&
              sleep 30 &&
            
              echo '--- APPLY MIGRATIONS ---' &&
              docker compose exec -T backend python manage.py migrate --noinput &&
            
              echo '--- COLLECTSTATIC ---' &&
              docker compose exec -T backend python manage.py collectstatic --noinput --clear &&
            
              echo '--- DEPLOYMENT COMPLETE ---'
            "