name: Deploy Django App

on:
  push:
    branches: ["main", "develop", "feature/homework_35_2"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/Homework_5

            echo "--- PULLING LATEST CODE ---"
            git pull origin main

            echo "--- REBUILD & RESTART DOCKER ---"
            docker compose down
            docker compose build
            docker compose up -d --remove-orphans

            echo "--- APPLYING MIGRATIONS ---"
            docker compose exec backend python manage.py migrate --noinput

            echo "--- COLLECTSTATIC ---"
            docker compose exec backend python manage.py collectstatic --noinput